---
- name: Converge
  hosts: all
  tasks:
    - name: molecule converge
      ansible.builtin.command: vector --version
      register: result
      failed_when: result.rc != 0
      changed_when: result.rc == 0
      ignore_errors: true
      when: ansible_virtualization_type not in ['docker', 'podman', 'container', 'containerd']
